service: patentpending-service-ipbackend

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2

functions:
  getIP:
    timeout: 15
    handler: main.getIP
    events:
      - http:
          method: GET
          path: ""
  notifyChangedIP:
    timeout: 15
    handler: main.notifyChangedIP
    events:
      - http:
          method: POST
          path: "notify"