service: patentpending-service-ipbackend

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  getIP:
    handler: main.getIP
    events:
      - http:
          method: GET
          path: ""

  notifyChangedIP:
    handler: main.notifyChangedIP
    events:
      - http:
          method: POST
          path: "notify"